[package]
name = "luxin_media_server"
version = "0.1.0"
authors = ["Benjamin Cecile <bencecile@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
comms_lib = { path = "../common_libs/comms_lib" }
